public with sharing class BrazillianAddress {

    @AuraEnabled
    public String cep;

    @AuraEnabled
    public String logradouro;

    @AuraEnabled
    public String numero;

    @AuraEnabled
    public String complemento;

    @AuraEnabled
    public String bairro;

    @AuraEnabled
    public String localidade;

    @AuraEnabled
    public String uf;
	
    @AuraEnabled
    public String ibge;

}